# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160419_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ders_Notlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
                ('dosya', models.FileField(upload_to=b'')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Ders_Videolari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
                ('dosya', models.FileField(upload_to=b'')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='fakulte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulte', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gorusler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sikayet_baslik', models.CharField(max_length=30)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Vize_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aciklama', models.TextField()),
                ('ad_soyad', models.CharField(max_length=30)),
                ('dosya', models.FileField(upload_to=b'')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolum')),
                ('fakulte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fakulte')),
            ],
        ),
        migrations.DeleteModel(
            name='a1',
        ),
        migrations.AddField(
            model_name='duyuru',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fakulte'),
        ),
        migrations.AddField(
            model_name='ders_videolari',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fakulte'),
        ),
        migrations.AddField(
            model_name='ders_notlari',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fakulte'),
        ),
    ]
